Handle tables with hyphens in their name
RobinBlomberg/kysely-codegen pull request #73
Opened 2023-04-30 06:52 UTC by yongtheskill

Currently, tables with hyphens in their name generate interfaces with hyphens in their name.
This is handled together with table names with periods in them.

2023-05-01 15:10 UTC, RobinBlomberg requested changes

2023-05-01 15:10 UTC, RobinBlomberg commented on src/collections/symbol-collection.ts
> +    symbolName = toPascalCase(id.replace(/\./g, '_').replace(/-/g, '_'));
Thanks for the contribution!

We could do this in one pass:

```suggestion
    symbolName = toPascalCase(id.replace(/[.-]/g, '_');
```

But perhaps we should really replace all characters that aren't allowed in JavaScript identifiers:

```suggestion
    symbolName = toPascalCase(id.replace(/[^a-zA-Z$_0-9]/g, '_');
```

And then add a prefix underscore if the identifier starts with `[0-9]`... probably needs a few tests so the logic is correct.

2023-05-01 17:15 UTC, yongtheskill commented
I dont know enough to implement the logic and tests :p

2023-06-15 10:56 UTC, grumd commented
Can't you generate Typescript interfaces with hyphens and periods anyway? https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCJzHARnAzigbwChlkBtAckywBsIBaEOAWwgoF0AuZAVxAGsQAewDuIANwlyVbHQB0TVh259BoiUQC+RIA

2023-10-11 05:48 UTC, merged

2023-10-14 14:31 UTC, RobinBlomberg commented
Published in `kysely-codegen@0.11.0`!